---
- name: Update all packages
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Update apt repository
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install OpenJDK
  ansible.builtin.apt:
    name: openjdk-17-jre
    state: present
  become: true

- name: Download Jenkins GPG key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
  become: true

- name: Add Jenkins APT repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/jenkins.list
    line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
    create: yes
  become: true

- name: Update apt repository again
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present
  become: true

- name: Start Jenkins service
  ansible.builtin.systemd:
    name: jenkins
    state: started
    enabled: yes
  become: true
